language: ruby
services:
- docker
script:
- pwd
- docker build -t mermithid .
- docker run -v /home/travis/build/project8/mermithid:/mermithid mermithid /bin/sh -c "source /usr/local/p8/mermithid/v1.1.7/setup.sh;\
  source /usr/local/p8/mermithid/v1.1.7/bin/this_phylloxera.sh; \
  source /usr/local/p8/mermithid/v1.1.7/bin/this_cicada.sh; \
  pwd; cd /mermithid; cd tests; bash test.sh"
notifications:
  slack:
    secure: L4e0yeIgPKvs9jnhMrdr5u2IMygwlNVYs0NHvANXtkAy2FIetzqBLcCHwxwHDr1r3XoNLCGdJN0rda/Ae/057nuz4NAbDzZW8Ui5GuAluw/Z8IPGrQM0JST5JSza4HkjI9ynL065eddbOhTR5aP2DkrUkPAaAC69HvgUPw7/UnZ8aSyzvL9LlNW7Yq3YvU5n/qtBW/YtLnewyJ/SaPSfWMfrm3eiYm8d1yoYg3AbdFC/89riFhBDRqgsaxsaVUjOsEXLeD6V2lHsv2eu/uR4MwP7IwBIABgexYBhKzOXKn9BUkAnwEzNDaLeIJuoCiI6ju2ReE0pUeiLxOMxgAapF8LM2AfWlZJ9LFBrayWpKF4UnRETWTMHw/d7Ued6Eooe5VqbRjXNxe+LHuLPmXDSAm2u7+8Kji2QMzBAvPKA2nOH3hIZ5VwiKpXAv+LHkKfnSyFeeozUFZh0BiVnV4I3+1IeE5Wrgq2P3o8V1fHkfzwxbEzf8Fv2YAVziwCrM6zYY/vlGWRiqph/riXwyxaZpw+yOGoLuSG291a511rdC+CHNgaMiya+A8v4IWCDR4l7OOYKOs/GKQmBJroI5NxE0vaNg+NGUW1a+3NHbkocLINAyAnCnw3lBFAsC1/E+ZOrb26xWiyCjSXxWLvcyq40XwhSNobjoim+g7K2RfcNk2w=
